#include "rational.hpp"

rational_exception::rational_exception() : logic_error("") {
    
}